### ISSUE TITLE
Not able to install in Multi User Mode

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/DiscoverKiller#11]
Hi there, 
I am trying to install Discover Killer apk in another user but not able to install it properly. I tried every possible way, firstly downloaded in main user and then enable through lsposed for another user. Secondly, just enabled through lsposed in main user and reboot, but nothing works 
![Screenshot_20220425-214805_Discover Killer](https://user-images.githubusercontent.com/70900505/165130861-46bda325-d431-425d-8399-c362b77aa21e.png)

**Comment by KieronQuinn** [comment]
If that warning is all that's blocking you, just press ignore. It's using an older Xposed detection method that no longer works with the parasitic manager.

**Comment by KieronQuinn** [comment]
This should be fixed in 3.0, so long as the Google app is installed on the same user as Discover Killer, since the self hook is no longer used.
