### ISSUE TITLE
Some Feed URLs don't load

### ISSUE THREAD

**Issue by rodrigoswz** [KieronQuinn/DiscoverKiller#13]
I tested some RSS URLs, some don't even load and others with text formatting seem incorrect in the article content.

Don't loading:
https://tecnoblog.net/feed/
https://canaltech.com.br/rss/

Edit 1:
https://www.apkmirror.com/apk/google-inc/feed/
Just out of curiosity, I tried it with an APKMirror RSS, it doesn't load in the feed either.

Content with HTML text formatting:
https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pKVGlnQVAB

![No loading](https://user-images.githubusercontent.com/14058427/180586337-7fe58ce6-1fa2-4ed9-825f-434bdb281a98.png)

![Text formatting](https://user-images.githubusercontent.com/14058427/180586578-49a6ccb0-f00f-46db-99e9-5ad58d294ca6.png)

**Comment by KieronQuinn** [comment]
RSS loading is handled by a library, this is not in scope for Discover Killer

https://github.com/prof18/RSS-Parser
