### ISSUE TITLE
The app is not working for me please help 

### ISSUE THREAD

**Issue by vaaibhavmishra** [KieronQuinn/DiscoverKiller#14]
I have installed lsposed and given permission of root and lsposed then also app is not working. I tried force stoping google app then also it is not working.
![Screenshot_20220725-001533_Discover Killer](https://user-images.githubusercontent.com/95367218/180662130-e5dff234-8d27-461a-be9c-4699073a7503.png)
![Screenshot_20220725-003242_Shell](https://user-images.githubusercontent.com/95367218/180662137-8af96bfe-926c-4a10-a5c3-1b4d64e56f29.png)

**Comment by KieronQuinn** [comment]
Try rebooting your device. If that doesn't work, there's nothing else I can do - this is caused by the hooking, so if that doesn't work then the module is not working and the message should not be bypassed.

**Comment by vaaibhavmishra** [comment]
Ok sir and thank you for your valuable response.
