### ISSUE TITLE
"Xposed module not enabled" Android 13

### ISSUE THREAD

**Issue by Majk720** [KieronQuinn/DiscoverKiller#17]
I enabled the module, granted root, but after entering the app i see a message "You must enable the (...) force stop the google app and retry". After stopping the google app the message still appears

**Comment by KieronQuinn** [comment]
This error means the hooks are not working and is not a Discover Killer problem. If the hooks are not working, the module cannot work and there is no fix.

**Comment by Martmists-GH** [comment]
How would I go about debugging this issue? Other LSPosed modules seem to work fine, and the Google app seems to instantly restart after it's forcibly stopped.
