### ISSUE TITLE
[Feature Request] Please add option to launch activity or app shortcut 

### ISSUE THREAD

**Issue by madhuraj0** [KieronQuinn/DiscoverKiller#18]
Hi,

Will it be possible to add an option to launch activity/ app shortcut?  

If you consider this feature request, please make sure to add system app activities as well like root activity launcher does it

**Comment by KieronQuinn** [comment]
#10 

System apps can be launched already.

**Comment by madhuraj0** [comment]
my main concern was about launching activities
