### ISSUE TITLE
Discover Killer Crashing 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/DiscoverKiller#19]
I have facing this [issue](https://user-images.githubusercontent.com/70900505/213846884-af7e7a53-f92b-47e4-9c23-1db33e73b1c8.mp4) in Discover Killer app, whenever I am trying to open, it takes me to lockscreen and gets difficult them to unlock it and it continues to stay same. I have never faced this issue earlier in Android 13. 

Android version ~ Android 13

Device ~ Realme 2 Pro

RO ~ Arrow OS

**Comment by KieronQuinn** [comment]
Please post a logcat, a video is not sufficient. Opening News works fine on my device.

**Comment by mjain234** [comment]
I think there was issue in latest Google app, when I downgraded the version to 13.23.14.29.arm64, it solves my problem.

**Comment by KieronQuinn** [comment]
I'm on a build of the Google app that's newer than the latest on APKmirror, and the most up to date News app and it works fine. I can only look into this any further with a log, otherwise I'll have to close this.

**Comment by KieronQuinn** [comment]
No log provided, closing
