### ISSUE TITLE
App not working (failed to connect to service)

### ISSUE THREAD

**Issue by s1w2a3** [KieronQuinn/DiscoverKiller#20]
Hello,
Thank you for your work on this amazing app. However, I can't use it on my phone. Google Discover works, but, when I activate the module in Lsposed, I can't swipe right anymore. I tried with different launchers, including those stated as "tested" in the readme.
I joined some logs. The last line ("XposedHooks(4848): Failed to connect to service, stopping self") is repeated about every 1/10 second after the first one (as seen in the screenshot).
Do you think there is anything to do to make it work?
Thank you in advance!

`01-29 10:38:58.230 I/LSPosed (4848): Loading xposed for com.google.android.googlequicksearchbox:search/10307
01-29 10:38:58.242 I/LSPosed-Bridge(4848): Loading module com.kieronquinn.app.discoverkiller from /data/app/~~Es22QLahuNh71-W9mbF34w==/com.kieronquinn.app.discoverkiller-bXsyHfV3ChLerZq9SClp5w==/base.apk
01-29 10:38:58.342 I/LSPosed-Bridge(4848):   Loading class com.kieronquinn.app.discoverkiller.xposed.Xposed
01-29 10:38:58.897 I/LSPosed (5027): Loading xposed for com.kieronquinn.app.discoverkiller/10296
01-29 10:38:58.900 I/LSPosed-Bridge(5027): Loading module com.kieronquinn.app.discoverkiller from /data/app/~~Es22QLahuNh71-W9mbF34w==/com.kieronquinn.app.discoverkiller-bXsyHfV3ChLerZq9SClp5w==/base.apk
01-29 10:38:59.030 I/LSPosed-Bridge(5027):   Loading class com.kieronquinn.app.discoverkiller.xposed.Xposed
01-29 10:39:02.001 I/LSPosed (5925): Loading xposed for com.google.android.googlequicksearchbox:interactor/10307
01-29 10:39:02.005 I/LSPosed-Bridge(5925): Loading module com.kieronquinn.app.discoverkiller from /data/app/~~Es22QLahuNh71-W9mbF34w==/com.kieronquinn.app.discoverkiller-bXsyHfV3ChLerZq9SClp5w==/base.apk
01-29 10:39:02.066 I/LSPosed-Bridge(5925):   Loading class com.kieronquinn.app.discoverkiller.xposed.Xposed
01-29 10:39:02.193 E/XposedHooks(4848): Failed to connect to service, stopping self`

![Screenshot_20230129-104756_MatLog~2](https://user-images.githubusercontent.com/68775901/215318409-d36749fc-ab3a-4ff0-a181-9113a312b6f7.png)

**Comment by KieronQuinn** [comment]
Force stop the Google App, then Discover Killer, then open Discover Killer and select Restart Overlay. This can happen sometimes when the overlay app is updated and the service fails to connect.

**Comment by s1w2a3** [comment]
Hi, thanks for you fast answer. I tried to do what you told me, but unfortunately it is still not working.
I realise I may not have been clear in my first message: I never managed to get Discoverkiller to work, but Google Discover works when Discoverkiller is deactivated.
Please tell me if you need any more logs or anything.

**Comment by KieronQuinn** [comment]
Unfortunately that means it's not compatible with your device then. The log message indicates it can't connect, and if the usual fix of force stopping doesn't work, there's nothing more I can do.
