### ISSUE TITLE
Xposed not working anymore 

### ISSUE THREAD

**Issue by Aleksanaa** [KieronQuinn/DiscoverKiller#23]
It complaints Xposed module not enabled like https://github.com/KieronQuinn/DiscoverKiller/issues/17.

Discover killer 3.0
Google 14.34.24.29.arm64
Lsposed 1.9.1(6900)

**Comment by KieronQuinn** [comment]
You already linked the duplicate, nothing has changed #17.

**Comment by Aleksanaa** [comment]
It's a regression after updating Google app.

**Comment by KieronQuinn** [comment]
No it isn't, nothing has changed in the Google app. This happens occasionally to some, it's always the local Xposed setup which has failed.

**Comment by Aleksanaa** [comment]
"Uninstall updates" does solve the issue. After uninstallation, Google version is 13.37.11.29.arm64.
