### ISSUE TITLE
Would it be possible to do this without having the google app installed?

### ISSUE THREAD

**Issue by Void-025** [KieronQuinn/DiscoverKiller#24]
I don't know much about xposed or android app development in general, but could it be possible to maybe redirect any attempt to open the google app, rather than replacing a part of the app itself, or something like that?
Personally I would prefer not to have the google app enabled on my phone at all, so it would be nice to be able to use this to replace it entirely.

**Comment by KieronQuinn** [comment]
Without the Google app you may not even need a module at all - you could have an app with the Google app's package name and run the redirect like that. It's not in scope for this app though as the Google app is included as stock on every GMS Android device and almost everyone would want to keep it that way, rather than uninstalling it _just_ for this.

**Comment by Void-025** [comment]
That's fair, but what about with the google app only disabled? That seems much more reasonable, and it's how I've had my phone since I got it (even before I started rooting and such).

Wouldn't it be possible to change it so that instead of having the google app redirect to this app, instead have any app that tries to open the google app instead open this one (I imagine they all must use some kind of identifier to open the google app, so replacing it should work?), that way it works both with or without the google app installed/disabled?
This might cause some problems for apps that try to open the google app for other reasons than the news, but I think that could be solved by just... not enabling the module on those apps.

Sorry if this is complete nonsense, I'm really just guessing based on my very limited understanding of how xposed hooks work.

Also, if this does turn out to be impossible, how much "google app" is actually needed for this app to hook correctly? Say I made an empty app with the google app's package name, would that be enough for this app to work properly? Or would it maybe need to have all the correct activities (or just the news one?), or more?

**Comment by KieronQuinn** [comment]
Not possible at all with it disabled. As for how much is required - very little, but that introduces other issues as other apps will be expecting the full app. 

Hooking each individual launcher app would be possible (and I've had it work that way in the past), but it's cumbersome and confusing for users so the approach currently in use is better. You also cannot use media overlays without hooking the Google app directly.
