### ISSUE TITLE
Inplement in launcher itself....

### ISSUE THREAD

**Issue by MillionsToOne** [KieronQuinn/DiscoverKiller#26]
I noticed that this specific app only works with Google Services and with the Google app installed while having the google app chosen in xposed module. After I used Smartspacer, its widget menu works just fine by choosing the launcher (in my case Trebuchet) in the Xposed module. Could this be implemented in this app so it would run without Google services?

**Comment by KieronQuinn** [comment]
Discover Killer replaces the code in the Google app to remove complexity and make it easier to apply. I won't be changing that.
