### ISSUE TITLE
'No Root'

### ISSUE THREAD

**Issue by gorbemark** [KieronQuinn/DiscoverKiller#27]
When I try to open the app, it say tge following: "Discover Killer requires root to work, make sure your device is rooted and you have granted root." and when i try to retry with the button below the message, nothing happens.
 Thank you, if you help!

**Comment by KieronQuinn** [comment]
Is your device rooted?

**Comment by gorbemark** [comment]
Well.. Im not familiar with the term 'rooted'. What is it, and what can I do about it to make your app work?

**Comment by KieronQuinn** [comment]
Discover Killer needs root and Xposed, I suggest you Google it as the method for getting it is different for every device.
