### ISSUE TITLE
Overlay like in smartspace

### ISSUE THREAD

**Issue by baianohak** [KieronQuinn/DiscoverKiller#29]
Smartspace does not need google app to hook the launcher and replace Google Feed, only xposed is necessary. can you do the same with Discovery killer? i use discovery killer but i don't use google app. and smartspace do it without Google app. 

thank you

**Comment by KieronQuinn** [comment]
This is due to a difference in methods. It's not possible to have the switcher for different apps using the Smartspacer method, so the Google app is required.

**Comment by baianohak** [comment]
Is possible to add a RSS plugin to smartspace? like homefeeder or rss overlay that exists in discovery killer?

**Comment by KieronQuinn** [comment]
If it conforms to the Smartspacer plugin SDK it would be. But you're better off just adding an RSS widget to Expanded Smartspace.
