### ISSUE TITLE
Just delete Google Feed... and all?

### ISSUE THREAD

**Issue by Quantom2** [KieronQuinn/DiscoverKiller#30]
Please, add a function that would completly disable anything on the left panel.

Yes, option to _replace_ this horrible stock google feed is good, I highli appritiate that, but personaly me, I don't wanna _replace_ it with something else at all. Just let it disapear and not angrying me anymore.

Now I can get almost similar result, but module just shows it's white fone and icon, purposing for me to set it up more, but I don't want to! Please, add an option that let you just leave a blank page, IDK, where would be  still completly still my wallpaper, bit no anything other.

Thanks sir, if you manage to add that I would be happy a lot (because my vendor made this horrible things UN-deletable, so only module or complete deleting of Google can help me, and I do not so much like last option)

**Comment by KieronQuinn** [comment]
Removing it entirely is the scope of the launcher, and most allow this. If yours doesn't, send a request to its developer.

**Comment by Quantom2** [comment]
I mean do not delete entirely left pannel, I understand that this is not possible on your side. I mean make module replace Google Feed with literaly nothing, just like when you set up to a app, it didn't open before you wont release finger, and I mean something that just will not call anything, exacly the same, but no any app. That would be great feacure for me
