### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by mjain234** [KieronQuinn/DiscoverKiller#32]
As you can see [here](https://github.com/user-attachments/assets/85c7be5a-2766-45d5-a593-86be23f98ab8), while opening the app which is set default in discover killer, it is not working. I have to reable the discover killer button to work that properly. 

Android version - 14

OS - Nothing OS 2.6.0

Phone - Nothing Phone 1

**Comment by KieronQuinn** [comment]
Please capture and send a log, ideally including the launcher starting (force stop it during capturing)

**Comment by mjain234** [comment]
This is the ![log](https://github.com/user-attachments/files/17936132/27_11-20-12-45_666.zip) file and a  [video](https://github.com/user-attachments/assets/c3ab8018-c676-475f-be76-83a74e076f05)

**Comment by KieronQuinn** [comment]
There's nothing in that log unfortunately. Since the launcher isn't logging anything of use and I don't have access to the device, there's nothing I can do, sorry.
