### ISSUE TITLE
it causes some bugs

### ISSUE THREAD

**Issue by kusti420** [KieronQuinn/DiscoverKiller#7]
it works mostly as intended but for me at least it also broke the recents menu. im not being shown any apps in recents menu. if you straight up open recents then there are no apps, but if you first launch whichever app youve set to open with it then it only shows white rectangles as apps in recents menu, no logos, no names.

![Screenshot_20210909-094722_Octavi_Launcher.png](https://user-images.githubusercontent.com/75937552/132638489-817ff2f8-ef64-40f7-9b38-36723699e1e6.png)

![Screenshot_20210909-100321_Octavi_Launcher.png](https://user-images.githubusercontent.com/75937552/132638617-b6db34c0-b5c3-494c-a6d5-087952a7e937.png)

**Comment by kusti420** [comment]
im using octavi os 2.6 GSI with stock "octavi" launcher, which is actually launcher3

**Comment by KieronQuinn** [comment]
This app has absolutely no interaction with the recents menu, please check that disabling it actually makes it work again.

**Comment by kusti420** [comment]
> This app has absolutely no interaction with the recents menu, please check that disabling it actually makes it work again.

idk, sth just broke, same problem even with it disabled now
