### ISSUE TITLE
Unable to work on android 10

### ISSUE THREAD

**Issue by KelvinCrag** [KieronQuinn/DiscoverKiller#8]
I tested the app on my Nokia 6.1 Plus (android one device) running on stock ROM android 10 and I noticed only the launch an app feature that works. 

The snapshot feature is not working, when I swipe left in home screen, nothing is shown, it behaves as if the "show google app" was disabled. 

Log: https://katb.in/nenerapafid.txt

**Comment by KieronQuinn** [comment]
There's probably not much point of me fixing this, as Snapshot is being killed off anyway

**Comment by KelvinCrag** [comment]
Kindly fix mate. Recently your module was marked as one of the best Xposed module by an article from XDA and there may be others in my category who would like to test this feature before it gets nuked. It would be said we didn't get a chance
